services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3306:3306"
    environment:
      - PORT=3000
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=jokipremium_ai_db
